require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolicitationsController do

  # This should return the minimal set of attributes required to create a valid
  # Solicitation. As you add validations to Solicitation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "solicitacao_tipos" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolicitationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all solicitations as @solicitations" do
      solicitation = Solicitation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:solicitations).should eq([solicitation])
    end
  end

  describe "GET show" do
    it "assigns the requested solicitation as @solicitation" do
      solicitation = Solicitation.create! valid_attributes
      get :show, {:id => solicitation.to_param}, valid_session
      assigns(:solicitation).should eq(solicitation)
    end
  end

  describe "GET new" do
    it "assigns a new solicitation as @solicitation" do
      get :new, {}, valid_session
      assigns(:solicitation).should be_a_new(Solicitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested solicitation as @solicitation" do
      solicitation = Solicitation.create! valid_attributes
      get :edit, {:id => solicitation.to_param}, valid_session
      assigns(:solicitation).should eq(solicitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Solicitation" do
        expect {
          post :create, {:solicitation => valid_attributes}, valid_session
        }.to change(Solicitation, :count).by(1)
      end

      it "assigns a newly created solicitation as @solicitation" do
        post :create, {:solicitation => valid_attributes}, valid_session
        assigns(:solicitation).should be_a(Solicitation)
        assigns(:solicitation).should be_persisted
      end

      it "redirects to the created solicitation" do
        post :create, {:solicitation => valid_attributes}, valid_session
        response.should redirect_to(Solicitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solicitation as @solicitation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitation.any_instance.stub(:save).and_return(false)
        post :create, {:solicitation => { "solicitacao_tipos" => "invalid value" }}, valid_session
        assigns(:solicitation).should be_a_new(Solicitation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitation.any_instance.stub(:save).and_return(false)
        post :create, {:solicitation => { "solicitacao_tipos" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solicitation" do
        solicitation = Solicitation.create! valid_attributes
        # Assuming there are no other solicitations in the database, this
        # specifies that the Solicitation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Solicitation.any_instance.should_receive(:update).with({ "solicitacao_tipos" => "" })
        put :update, {:id => solicitation.to_param, :solicitation => { "solicitacao_tipos" => "" }}, valid_session
      end

      it "assigns the requested solicitation as @solicitation" do
        solicitation = Solicitation.create! valid_attributes
        put :update, {:id => solicitation.to_param, :solicitation => valid_attributes}, valid_session
        assigns(:solicitation).should eq(solicitation)
      end

      it "redirects to the solicitation" do
        solicitation = Solicitation.create! valid_attributes
        put :update, {:id => solicitation.to_param, :solicitation => valid_attributes}, valid_session
        response.should redirect_to(solicitation)
      end
    end

    describe "with invalid params" do
      it "assigns the solicitation as @solicitation" do
        solicitation = Solicitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitation.to_param, :solicitation => { "solicitacao_tipos" => "invalid value" }}, valid_session
        assigns(:solicitation).should eq(solicitation)
      end

      it "re-renders the 'edit' template" do
        solicitation = Solicitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Solicitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitation.to_param, :solicitation => { "solicitacao_tipos" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solicitation" do
      solicitation = Solicitation.create! valid_attributes
      expect {
        delete :destroy, {:id => solicitation.to_param}, valid_session
      }.to change(Solicitation, :count).by(-1)
    end

    it "redirects to the solicitations list" do
      solicitation = Solicitation.create! valid_attributes
      delete :destroy, {:id => solicitation.to_param}, valid_session
      response.should redirect_to(solicitations_url)
    end
  end

end
