require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolicitacaoTiposController do

  # This should return the minimal set of attributes required to create a valid
  # SolicitacaoTipo. As you add validations to SolicitacaoTipo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tipo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SolicitacaoTiposController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all solicitacao_tipos as @solicitacao_tipos" do
      solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:solicitacao_tipos).should eq([solicitacao_tipo])
    end
  end

  describe "GET show" do
    it "assigns the requested solicitacao_tipo as @solicitacao_tipo" do
      solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
      get :show, {:id => solicitacao_tipo.to_param}, valid_session
      assigns(:solicitacao_tipo).should eq(solicitacao_tipo)
    end
  end

  describe "GET new" do
    it "assigns a new solicitacao_tipo as @solicitacao_tipo" do
      get :new, {}, valid_session
      assigns(:solicitacao_tipo).should be_a_new(SolicitacaoTipo)
    end
  end

  describe "GET edit" do
    it "assigns the requested solicitacao_tipo as @solicitacao_tipo" do
      solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
      get :edit, {:id => solicitacao_tipo.to_param}, valid_session
      assigns(:solicitacao_tipo).should eq(solicitacao_tipo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SolicitacaoTipo" do
        expect {
          post :create, {:solicitacao_tipo => valid_attributes}, valid_session
        }.to change(SolicitacaoTipo, :count).by(1)
      end

      it "assigns a newly created solicitacao_tipo as @solicitacao_tipo" do
        post :create, {:solicitacao_tipo => valid_attributes}, valid_session
        assigns(:solicitacao_tipo).should be_a(SolicitacaoTipo)
        assigns(:solicitacao_tipo).should be_persisted
      end

      it "redirects to the created solicitacao_tipo" do
        post :create, {:solicitacao_tipo => valid_attributes}, valid_session
        response.should redirect_to(SolicitacaoTipo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solicitacao_tipo as @solicitacao_tipo" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolicitacaoTipo.any_instance.stub(:save).and_return(false)
        post :create, {:solicitacao_tipo => { "tipo" => "invalid value" }}, valid_session
        assigns(:solicitacao_tipo).should be_a_new(SolicitacaoTipo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolicitacaoTipo.any_instance.stub(:save).and_return(false)
        post :create, {:solicitacao_tipo => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solicitacao_tipo" do
        solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
        # Assuming there are no other solicitacao_tipos in the database, this
        # specifies that the SolicitacaoTipo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SolicitacaoTipo.any_instance.should_receive(:update).with({ "tipo" => "MyString" })
        put :update, {:id => solicitacao_tipo.to_param, :solicitacao_tipo => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested solicitacao_tipo as @solicitacao_tipo" do
        solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
        put :update, {:id => solicitacao_tipo.to_param, :solicitacao_tipo => valid_attributes}, valid_session
        assigns(:solicitacao_tipo).should eq(solicitacao_tipo)
      end

      it "redirects to the solicitacao_tipo" do
        solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
        put :update, {:id => solicitacao_tipo.to_param, :solicitacao_tipo => valid_attributes}, valid_session
        response.should redirect_to(solicitacao_tipo)
      end
    end

    describe "with invalid params" do
      it "assigns the solicitacao_tipo as @solicitacao_tipo" do
        solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolicitacaoTipo.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitacao_tipo.to_param, :solicitacao_tipo => { "tipo" => "invalid value" }}, valid_session
        assigns(:solicitacao_tipo).should eq(solicitacao_tipo)
      end

      it "re-renders the 'edit' template" do
        solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolicitacaoTipo.any_instance.stub(:save).and_return(false)
        put :update, {:id => solicitacao_tipo.to_param, :solicitacao_tipo => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solicitacao_tipo" do
      solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
      expect {
        delete :destroy, {:id => solicitacao_tipo.to_param}, valid_session
      }.to change(SolicitacaoTipo, :count).by(-1)
    end

    it "redirects to the solicitacao_tipos list" do
      solicitacao_tipo = SolicitacaoTipo.create! valid_attributes
      delete :destroy, {:id => solicitacao_tipo.to_param}, valid_session
      response.should redirect_to(solicitacao_tipos_url)
    end
  end

end
